---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eirini
  namespace: eirini-system
data:
  opi.yml: |
    opi:
      app_namespace: eirini
      registry_address: "<registry-url>"

      eirini_service_name: "eirini-opi"
      registry_secret_name: registry-credentials
      eirini_address: "https://eirini_service_name.EIRINI_NAMESPACE.svc.cluster.local:8085"
      #EIRINI_NAMESPACE can be an env variable in Eirini
      #we can get it using the downward api

      cc_uploader_secret_name: cc-uploader
      cc_uploader_cert_path: cc_uploader.crt
      cc_uploader_key_path: cc_uploader.key
      cc_uploader_ca_path: cc_uploader.ca

      cc_cert_path: "/etc/eirini/secrets/cc.crt"
      cc_key_path: "/etc/eirini/secrets/cc.key"
      cc_ca_path: "/etc/eirini/secrets/cc.ca"

      client_ca_path: "/etc/eirini/secrets/eirini.ca"
      server_cert_path: "/etc/eirini/secrets/eirini-server.crt"
      server_key_path: "/etc/eirini/secrets/eirini-server.key"

      staging: # This is only needed if you want to use native staging
        eirini_client_secret_name: eirini-client
        eirini_client_cert_path: eirini-client.crt
        eirini_client_key_path: eirini-client.key
        eirini_client_ca_path: eirini.ca

      downloader_image: "eirini/recipe-downloader@sha256:asdasda"
      executor_image: "eirini/recipe-executor@sha256:asdadasd"
      uploader_image: "eirini/recipe-uploader@sha256:sadasdas"

      rootfs_version: "<rootfs-version>"

      tls_port: 8085

      allow_plaintext: false
      plaintext_port: 8085

      disk_limit_mb: 256 # to be removed
      application_service_account: eirini
      staging_service_account: eirini-staging
      allow_run_image_as_root: false
  routing.yml: |
    app_namespace: eirini
    nats_ip: "<nats-address>" # rename to nats_address
    nats_port: 4222
  metrics.yml: |
    app_namespace: eirini
    loggregator_address: "<loggregator-address>:<port>"
    doppler_cert_path: "/etc/eirini/secrets/doppler.crt"
    doppler_key_path: "/etc/eirini/secrets/doppler.key"
    doppler_ca_path: "/etc/eirini/secrets/doppler.ca"
  events.yml: |
    app_namespace: eirini
    cc_internal_api: "https://<cc_internal_api>:<port>"
    cc_cert_path: "/etc/eirini/secrets/cc.crt"
    cc_key_path: "/etc/eirini/secrets/cc.key"
    cc_ca_path: "/etc/eirini/secrets/cc.ca"
  staging-reporter.yml: |
    app_namespace: eirini
    eirini_cert_path: "/etc/eirini/secrets/eirini-client.crt"
    eirini_key_path: "/etc/eirini/secrets/eirini-client.key"
    ca_path: "/etc/eirini/secrets/eirini.ca"
  task-reporter.yml: |
    app_namespace: eirini
    cc_cert_path: "/etc/eirini/secrets/cc.crt"
    cc_key_path: "/etc/eirini/secrets/cc.key"
    ca_path: "/etc/eirini/secrets/cc.ca"
  lrp-controller.yml: |
    app_namespace: eirini
    eirini_service_name: "eirini-opi"
    port: 8085
    eirini_cert_path: "/etc/eirini/secrets/eirini-client.crt"
    eirini_key_path: "/etc/eirini/secrets/eirini-client.key"
    ca_path: "/etc/eirini/secrets/eirini.ca"
