---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "eirini"
data:
  opi.yml: |
    opi:
      app_namespace: eirini
      registry_address: "<registry-url>"

      eirini_service_name: "eirini-opi"

      downloader_image: "eirini/recipe-downloader@sha256:asdasda"
      executor_image: "eirini/recipe-executor@sha256:asdadasd"
      uploader_image: "eirini/recipe-uploader@sha256:sadasdas"

      rootfs_version: "<rootfs-version>"

      tls_port: 8085

      allow_plaintext: false
      plaintext_port: 8085

      disk_limit_mb: 256 # to be removed
      application_service_account: eirini
      staging_service_account: eirini-staging
      allow_run_image_as_root: false
  routing.yml: |
    app_namespace: eirini
    nats_ip: "<nats-address>" # rename to nats_address
    nats_port: 4222
  metrics.yml: |
    app_namespace: eirini
    loggregator_address: "<loggregator-address>:<port>"
  events.yml: |
    app_namespace: eirini
    cc_internal_api: "https://<cc_internal_api>:<port>"
  staging-reporter.yml: |
    app_namespace: eirini
  task-reporter.yml: |
    app_namespace: eirini
  lrp-controller.yml: |
    app_namespace: eirini
    eirini_service_name: "eirini-opi"
    port: 8085
