---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini
  namespace: eirini-system
spec:
  selector:
    matchLabels:
      name: "eirini"
  template:
    metadata:
      labels:
        name: "eirini"
        eirinifs_version: "v158.0.0"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "opi"
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini"
            items:
              - key: opi.yml
                path: opi.yml
        - name: cf-secrets
          projected:
            sources:
              - secret:
                  name: "capi"
                  items:
                    - key: "cc.crt"
                      path: cc.crt
                    - key: "cc.key"
                      path: cc.key
                    - key: "cc.ca"
                      path: cc.ca
              - secret:
                  name: "eirini-server"
                  items:
                    - key: "eirini-server.crt"
                      path: eirini-server.crt
                    - key: "eirini-server.key"
                      path: eirini-server.key
                    - key: "eirini.ca"
                      path: eirini.ca
      securityContext:
        runAsNonRoot: true
      containers:
        - name: opi
          image: eirini/opi@sha256:55c68ebf835b9b6cc7edb79205f8498fe1adc79be70de7330271139011317869
          imagePullPolicy: Always
          volumeMounts:
            - name: config-map-volume
              mountPath: /etc/eirini/config
            - name: cf-secrets
              mountPath: /etc/eirini/secrets
          ports:
            - containerPort: 8085
              name: https
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
