---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-controller
  namespace: eirini-core
spec:
  selector:
    matchLabels:
      name: eirini-controller
  template:
    metadata:
      labels:
        name: eirini-controller
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-controller
      securityContext:
        runAsNonRoot: true
      containers:
      - name: eirini-controller
        image: eirini/eirini-controller@sha256:a7fd055a8f3d8d07a9f3e92cee9cd2055e2a049a9eb955f486f6536f067a4d70
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/config
      volumes:
        - name: config-map-volume
          configMap:
            name: "opi"
            items:
            - key: opi.yml
              path: eirini-controller.yml
