---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini
  namespace: eirini-core
spec:
  selector:
    matchLabels:
      name: eirini
  template:
    metadata:
      labels:
        name: eirini
        eirinifs_version: v75.0.0
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: opi
      volumes:
        - name: config-map-volume
          configMap:
            name: opi
        - name: cf-secrets
          projected:
            sources:
            # uncomment for cloud controller with tls
            #
            # - secret:
            #     name: capi-tls
            #     items:
            #     - key: cc.crt
            #       path: cc.crt
            #     - key: cc.key
            #       path: cc.key
            #     - key: cc.ca
            #       path: cc.ca
            - secret:
                name: eirini-tls
                items:
                - key: tls.crt
                  path: eirini-server.crt
                - key: tls.key
                  path: eirini-server.key
                - key: tls.ca
                  path: eirini.ca
      securityContext:
        runAsNonRoot: true
      containers:
      - name: opi
        image: eirini/opi@sha256:1ddcd74e8b6646f03d280d0dca40bc3a51e9bf6d950176a44683a9496ece38b5
        imagePullPolicy: Always
        volumeMounts:
        - name: config-map-volume
          mountPath: /workspace/jobs/opi/config
        - name: cf-secrets
          mountPath: /workspace/jobs/opi/secrets
        ports:
        - containerPort: 8085
          name: https
        resources:
          requests:
            cpu: 20m
            memory: 20
