---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opi
  namespace: eirini-core
data:
  opi.yml: |
    opi:
      app_namespace: eirini-workloads
      tls_port: 8085

      # TODO: test with kubecf
      registry_address: REGISTRY.DOMAIN:PORT
      registry_secret_name: registry-credentials
      eirini_address: https://eirini.eirini-core.svc.cluster.local:8085

      downloader_image: eirini/recipe-downloader@sha256:96eea8a7c7cb53b54678d7f26ab0c1897b1b699297c4b75d64a93b4833048554
      executor_image: eirini/recipe-executor@sha256:c073e375d891259d91dd63148ac8e880098d9f298304954318818a197d1163b3
      uploader_image: eirini/recipe-uploader@sha256:af3d57790d3e6fbcc719e64dd553a2b410b2f7036bc1903aac339ce96144d8dc

      cc_uploader_secret_name: cc-uploader-cert
      cc_uploader_cert_path: cc-uploader.crt
      cc_uploader_key_path: cc-uploader.key

      client_certs_secret_name: client-cert
      client_cert_path: client-cert.crt
      client_key_path: client-cert.key

      ca_cert_secret_name: ca-cert
      ca_cert_path: ca.crt

      staging_service_account: eirini-staging
      # end of TODO

      client_ca_path: /workspace/jobs/opi/secrets/eirini.ca
      server_cert_path: /workspace/jobs/opi/secrets/eirini-server.crt
      server_key_path: /workspace/jobs/opi/secrets/eirini-server.key

      # if cc_tls_disable: true, remove capi secret from deployment.yml
      cc_tls_disabled: true
      # if cc_tls_disable: false, uncomment lines below
      # cc_cert_path: "/workspace/jobs/opi/secrets/cc.crt"
      # cc_key_path: "/workspace/jobs/opi/secrets/cc.key"
      # cc_ca_path: "/workspace/jobs/opi/secrets/cc.ca"

      rootfs_version: v75.0.0
      disk_limit_mb: 2048
      application_service_account: eirini
      allow_run_image_as_root: false
      unsafe_allow_automount_service_account_token: false
      serve_plaintext: false
