apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-metrics
  namespace: eirini-system
spec:
  selector:
    matchLabels:
      name: eirini-metrics
  template:
    metadata:
      labels:
        name: eirini-metrics
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-metrics
      volumes:
        - name: config-map-volume
          configMap:
            name: eirini
            items:
              - key: metrics.yml
                path: metrics.yml
        - name: cf-secrets
          secret:
            secretName: doppler
            items:
              - key: doppler.crt
                path: doppler.crt
              - key: doppler.key
                path: doppler.key
              - key: doppler.ca
                path: doppler.ca
      securityContext:
        runAsNonRoot: true
      containers:
        - name: metrics-collector
          image: eirini/metrics-collector@sha256:asdasdasadasd
          imagePullPolicy: Always
          volumeMounts:
            - name: config-map-volume
              mountPath: /etc/eirini/config
            - name: cf-secrets
              mountPath: /etc/eirini/secrets
          resources:
            requests:
              cpu: 15m
              memory: 15Mi
