
language: generic

dist: bionic
sudo: false

env:
  global:
    - HELM_VERSION="v2.14.3"

install:
  - wget http://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
  - mkdir -p /tmp/bin
  - tar xzf /tmp/helm.tar.gz -C /tmp/bin --strip-components=1
  - chmod +x /tmp/bin/helm
  - export PATH=/tmp/bin:$PATH

before_script:
  - helm init --client-only
  - helm repo add bits https://cloudfoundry-incubator.github.io/bits-service-release/helm
script:
  - ./scripts/helm-lint.sh
