apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-routing
  namespace: eirini-system
spec:
  selector:
    matchLabels:
      name: eirini-routing
  template:
    metadata:
      labels:
        name: eirini-routing
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-routing
      volumes:
        - name: config-map-volume
          configMap:
            name: eirini
            items:
            - key: routing.yml
              path: routing.yml
      securityContext:
        runAsNonRoot: true
      containers:
      - name: route-collector
        image: eirini/route-collector@sha256:asdasdasd
        imagePullPolicy: Always
        env:
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nats
              key: password
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/
        resources:
          requests:
            cpu: 30m
            memory: 45Mi
      - name: route-pod-informer
        image: eirini/route-pod-informer@sha256:asdasdasdas
        imagePullPolicy: Always
        env:
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nats
              key: password
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/
        resources:
          requests:
            cpu: 30m
            memory: 45Mi
      - name: route-statefulset-informer
        image: eirini/route-statefulset-informer@sha256:sdasdasdas
        imagePullPolicy: Always
        env:
        - name: NATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nats
              key: password
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/
        resources:
          requests:
            cpu: 30m
            memory: 45Mi
