---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-lrp-controller
  namespace: eirini-system
spec:
  selector:
    matchLabels:
      name: eirini-lrp-controller
  template:
    metadata:
      labels:
        name: eirini-lrp-controller
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: lrp-controller
      securityContext:
        runAsNonRoot: true
      containers:
        - name: lrp-controller
          image: eirini/lrp-controller@sha256:asdasda
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 15m
              memory: 15Mi
          volumeMounts:
            - name: config-map-volume
              mountPath: /etc/eirini/config
            - name: cf-secrets
              mountPath: /etc/eirini/secrets
      volumes:
        - name: config-map-volume
          configMap:
            name: eirini
            items:
              - key: lrp-controller.yml
                path: lrp-controller.yml
        - name: cf-secrets
          secret:
            secretName: eirini-client
            items:
              - key: eirini-client.crt
                path: eirini-client.crt
              - key: eirini-client.key
                path: eirini-client.key
              - key: eirini.ca
                path: eirini-client.ca
