{{- if .Values.opi.eiriniController.enable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: eirini-controller
  template:
    metadata:
      labels:
        name: eirini-controller
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-controller
      securityContext:
        runAsNonRoot: true
      containers:
      - name: eirini-controller
        {{- if .Values.opi.eirini_controller_image }}
        image: {{ .Values.opi.eirini_controller_image }}:{{ .Values.opi.eirini_controller_image_tag }}
        {{- else }}
        image: eirini/eirini-controller@{{ .Files.Get "versions/eirini-controller" }}
        {{- end }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/config
        - name: cf-secrets
          mountPath: /etc/eirini/secrets
      volumes:
        - name: config-map-volume
          configMap:
            name: "eirini"
            items:
            - key: eirini-controller.yml
              path: eirini-controller.yml
        - name: cf-secrets
          secret:
            secretName: "{{ .Values.opi.eiriniController.tls.secretName }}"
            items:
            - key: "{{ .Values.opi.eiriniController.tls.certPath }}"
              path: eirini-client.crt
            - key: "{{ .Values.opi.eiriniController.tls.keyPath }}"
              path: eirini-client.key
            - key: "{{ .Values.opi.eiriniController.tls.caPath }}"
              path: eirini-client.ca
{{- end }}
