{{- if .Values.opi.kubecf.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: use-native-eirini 
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: operations
data:
  ops: |
    # Remove the whole diego-cell instance group.
    - type: remove
      path: /instance_groups/name=diego-cell

    # Remove bbs from diego-api.
    # TODO: remove bbs in the future - when the clock and worker no longer need it.
    # - type: remove
    #   path: /instance_groups/name=diego-api/jobs/name=bbs

    # Remove auctioneer, tps and ssh_proxy from scheduler.
    - type: remove
      path: /instance_groups/name=auctioneer
    - type: remove
      path: /instance_groups/name=scheduler/jobs/name=tps
    - type: remove
      path: /instance_groups/name=scheduler/jobs/name=ssh_proxy

    # Enable OPI in CC
    # cloud_controller_ng
    - type: replace
      path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/enabled?
      value: true
    - type: replace
      path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/url?
      value: https://eirini-opi.{{ .Release.Namespace }}.svc.cluster.local:8085 
    - type: replace
      path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/opi_staging?
      value: true
    - type: replace
      path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/client_cert?
      value: ((eirini_tls_client_cert.certificate))
    - type: replace
      path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/client_key?
      value: ((eirini_tls_client_cert.private_key))
    - type: replace
      path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/opi?/ca_cert?
      value: ((eirini_tls_server_cert.ca))
    
    # cloud_controller_worker
    - type: replace
      path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/enabled?
      value: true
    - type: replace
      path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/url?
      value: https://eirini-opi.{{ .Release.Namespace }}.svc.cluster.local:8085 
    - type: replace
      path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/opi_staging?
      value: true
    - type: replace
      path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/client_cert?
      value: ((eirini_tls_client_cert.certificate))
    - type: replace
      path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/client_key?
      value: ((eirini_tls_client_cert.private_key))
    - type: replace
      path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/opi?/ca_cert?
      value: ((eirini_tls_server_cert.ca))
    
    # cloud_controller_clock
    - type: replace
      path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/enabled?
      value: true
    - type: replace
      path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/url?
      value: https://eirini-opi.{{ .Release.Namespace }}.svc.cluster.local:8085 
    - type: replace
      path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/opi_staging?
      value: true
    - type: replace
      path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/client_cert?
      value: ((eirini_tls_client_cert.certificate))
    - type: replace
      path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/client_key?
      value: ((eirini_tls_client_cert.private_key))
    - type: replace
      path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/opi?/ca_cert?
      value: ((eirini_tls_server_cert.ca))

    - type: replace
      path: /variables/name=eirini_tls_server_cert?
      value:
        name: eirini_tls_server_cert
        type: certificate
        options:
          ca: service_cf_internal_ca
          common_name: "eirini-opi"
          alternative_names:
          - eirini-opi.kubecf.svc.cluster.local
          extended_key_usage:
          - server_auth
    - type: replace
      path: /variables/name=eirini_tls_client_cert?
      value:
        name: eirini_tls_client_cert
        type: certificate
        options:
          ca: service_cf_internal_ca
          common_name: cloud_controller
          extended_key_usage:
          - client_auth
{{- end }}
