---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "lrpnamespace"
  namespace: "{{ .ReleaseNamespace }}"
data:
  eirini-role.yml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: eirini-role
      namespace: "{{ .LrpNamespace }}"
    rules:
    - apiGroups:
      - batch
      resources:
      - jobs
      verbs:
      - create
      - delete
      - list
    - apiGroups:
      - apps
      resources:
      - statefulsets
      verbs:
      - create
      - update
      - delete
      - list
    - apiGroups:
      - ""
      resources:
      - events
      verbs:
      - list
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - list
      - delete
    - apiGroups:
      - policy
      resources:
      - poddisruptionbudgets
      verbs:
      - create
      - delete
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - create
      - delete
  eirini-role-binding.yml: |
    # Bind to the default service account
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: eirini-rolebinding
      namespace: "{{ .LrpNamespace }}"
    roleRef:
      kind: Role
      name: eirini-role
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: opi
      namespace: "{{ .ReleaseNamespace }}"
