apiVersion: batch/v1
kind: Job
metadata:
  name: "rootfs-patcher-{{ .Values.opi.rootfs_version }}"
spec:
  template:
    spec:
      initContainers:
      - name: bits-waiter
        {{- if (typeOf .Values.opi.bits_waiter_image) "<nil>" }}
        image: eirini/bits-waiter@{{ .Files.get "versions/bits-waiter" }}
        {{- else }}
        image: {{.Values.opi.bits_waiter_image}}:{{ .Values.opi.image_tag }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        command:
        - /bits-waiter
        - --namespace=scf
        - --timeout={{ .Values.opi.rootfs_patcher_timeout }}
      containers:
      - name: patch
        command:
        - /rootfs-patcher
        - --namespace={{ .Values.opi.namespace }}
        - --rootfs-version={{ .Values.opi.rootfs_version }}
        {{- if (typeOf .Values.opi.rootfs_patcher_image) "<nil>" }}
        image: eirini/rootfs-patcher@{{ .Files.get "versions/rootfs-patcher" }}
        {{- else }}
        image: {{.Values.opi.rootfs_patcher_image}}:{{ .Values.opi.image_tag }}
        {{- end }}
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      serviceAccount: opi
      serviceAccountName: opi
