---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "eirini"
data:
  opi.yml: |
    opi:
      app_namespace: eirini
      registry_address: "<registry-url>"

      downloader_image: "eirini/recipe-downloader@sha256:asdasda"
      executor_image: "eirini/recipe-executor@sha256:asdadasd"
      uploader_image: "eirini/recipe-uploader@sha256:sadasdas"

      rootfs_version: "<rootfs-version>"

      tls_port: 8085
      disk_limit_mb: {{ .Values.opi.disk_limit_mb }}
      application_service_account: eirini
      staging_service_account: eirini-staging
      allow_run_image_as_root: false
  routing.yml: |
    app_namespace: {{ .Values.opi.namespace }}
    nats_ip: "{{ .Values.opi.routing.nats.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local"
    nats_port: 4222
  metrics.yml: |
    app_namespace: {{ .Values.opi.namespace }}
    loggregator_address: "{{ .Values.opi.logs.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local:8082"
    loggergator_cert_path: "/etc/eirini/secrets/doppler.crt"
    loggregator_key_path: "/etc/eirini/secrets/doppler.key"
    loggregator_ca_path: "/etc/eirini/secrets/doppler.ca"
  events.yml: |
    app_namespace: {{ .Values.opi.namespace }}
    cc_internal_api: "https://{{ .Values.opi.cc_api.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local:9023"
    cc_cert_path: "/etc/eirini/secrets/cc.crt"
    cc_key_path: "/etc/eirini/secrets/cc.key"
    cc_ca_path: "/etc/eirini/secrets/cc.ca"
  staging-reporter.yml: |
    app_namespace: {{ .Values.opi.namespace }}
    eirini_cert_path: "/etc/eirini/secrets/eirini-client.crt"
    eirini_key_path: "/etc/eirini/secrets/eirini-client.key"
    ca_path: "/etc/eirini/secrets/eirini-client.ca"
  task-reporter.yml: |
    app_namespace: {{ .Values.opi.namespace }}
    cc_cert_path: "/etc/eirini/secrets/cc.crt"
    cc_key_path: "/etc/eirini/secrets/cc.key"
    ca_path: "/etc/eirini/secrets/cc.ca"
  lrp-controller.yml: |
    app_namespace: {{ .Values.opi.namespace }}
    eirini_uri: "https://eirini-opi.{{ .Release.Namespace }}.svc.cluster.local:8085"
    eirini_cert_path: "/etc/eirini/secrets/eirini-client.crt"
    eirini_key_path: "/etc/eirini/secrets/eirini-client.key"
    ca_path: "/etc/eirini/secrets/eirini-client.ca"
