---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-task-reporter
  namespace: eirini-system
spec:
  selector:
    matchLabels:
      name: eirini-task-reporter
  template:
    metadata:
      labels:
        name: eirini-task-reporter
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-task-reporter
      securityContext:
        runAsNonRoot: true
      containers:
      - name: task-reporter
        image: eirini/task-reporter@sha256:sadsdasda
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/config
        - name: cf-secrets
          mountPath: /etc/eirini/secrets
      volumes:
        - name: config-map-volume
          configMap:
            name: eirini
            items:
            - key: task-reporter.yml
              path: task-reporter.yml
        - name: cf-secrets
          secret:
             secretName: capi
             items:
             - key: cc.crt
               path: cc.crt
             - key: cc.key
               path: cc.key
             - key: cc.ca
               path: cc.ca
