# create-certs
---
kind: Job
apiVersion: batch/v1
metadata:
  name: create-certs
spec:
  template:
    metadata:
      name: create-certs
    spec:
      serviceAccountName: "opi"
      restartPolicy: OnFailure
      containers:
      - name: create-certs
        env:
        - name: REGISTRY
          value: '{{ template "eirini-chart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local'
        image: eirini/certs-generate
        imagePullPolicy: Always

# copy-certs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-copier
spec:
  template:
    spec:
      serviceAccountName: "opi"
      restartPolicy: OnFailure
      volumes:
      - name: host-docker
        hostPath:
          path: /etc/docker
          type: Directory
      containers:
      - name: copy-certs
        env:
        - name: REGISTRY
          value: '{{ template "eirini-chart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local'
        image: eirini/certs-copy
        volumeMounts:
        - name: host-docker
          mountPath: /workspace/docker
