{{- if .Values.ingress.enabled -}}
{{- $fullName := include "eirini-chart.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "eirini-chart.name" . }}
    chart: {{ template "eirini-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.opi.host }}
      http:
        paths:
          - path: {{ .Values.ingress.opi.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.ingress.opi.port }}
    - host: {{ .Values.ingress.registry.host }}
      http:
        paths:
          - path: {{ .Values.ingress.registry.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.ingress.registry.port }}
{{- end }}
