apiVersion: v1
kind: Service
metadata:
  name: {{ template "eirini-chart.fullname" . }}
  labels:
    app: {{ template "eirini-chart.name" . }}
    chart: {{ template "eirini-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.opi.port }}
      targetPort: 8085
      protocol: TCP
      name: opi
    - port: {{ .Values.service.registry.port }}
      targetPort: 8080
      protocol: TCP
      name: registry
  selector:
    app: {{ template "eirini-chart.name" . }}
    release: {{ .Release.Name }}
